# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano
#     shield: reviung41
#
---
# board: [seeeduino_xiao, xiao_ble, seeeduino_xiao_rp2040]
# board: [xiao_ble]
# shield:
#   - hammer40
#   - hana_central_left
#   - hana_peripheral_left
#   - hana_peripheral_right
include:
  - board: xiao_ble
    shield: settings_reset
  - board: nice_nano
    shield: settings_reset
    # Hammer
  - board: xiao_ble
    shield: hammer40
    snippet: studio-rpc-usb-uart
    # Hana
  - board: nice_nano
    shield: hana_central_dongle
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: hana_peripheral_left
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: hana_central_left
    snippet: studio-rpc-usb-uart
  - board: xiao_ble
    shield: hana_peripheral_right
    snippet: studio-rpc-usb-uart
    # Corne Wireless
  - board: nice_nano
    shield: acorn_central_dongle
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: acorn_peripheral_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: acorn_central_left
    snippet: studio-rpc-usb-uart
  - board: nice_nano
    shield: acorn_peripheral_right
    snippet: studio-rpc-usb-uart
