# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
# board: [seeeduino_xiao, seeeduino_xiao_ble, seeeduino_xiao_rp2040]
# board: [seeeduino_xiao_ble]
# shield:
#   - hammer40
#   - hana_central_left
#   - hana_peripheral_left
#   - hana_peripheral_right
include:
  # - board: seeeduino_xiao_ble
  #   shield: settings_reset
  # - board: nice_nano_v2
  #   shield: settings_reset
  # - board: nice_nano_v2
  #   shield: hana_central_dongle
  # - board: nice_nano_v2
  #   shield: acorn_central_left
  # - board: nice_nano_v2
  #   shield: acorn_peripheral_right
  - board: seeeduino_xiao_ble
    shield: hammer40
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: hammer40_xiao_ble_studio 
  - board: seeeduino_xiao_rp2040
    shield: hammer40
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: hammer40_xiao_rp2040_studio 
  - board: seeeduino_xiao_ble
    shield: hana_central_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: hana_left_xiao_ble_studio 
  - board: seeeduino_xiao_ble
    shield: hana_peripheral_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: hana_right_xiao_ble_studio 
  - board: nice_nano_v2
    shield: acorn_central_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: acorn_left_nice_nano_studio 
  - board: nice_nano_v2
    shield: acorn_peripheral_right
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: acorn_right_nice_nano_studio 